#!/usr/bin/env bash

BASEDIR=$(pwd)

AUTOLOADS=autoload
BUNDLES=bundle

SOLARIZED=mutt-colors-solarized
SOLARIZED_GIT=https://github.com/altercation/$SOLARIZED.git

MKDIR='mkdir -p'
RM='rm -f'
LN='ln -s'
CLONE='git clone'
UPDATE='git pull'

function setup_solarized()
{
  if [[ -d $SOLARIZED ]]; then
    echo updating solarized repo
    cd $SOLARIZED && $UPDATE && cd -
  else
    echo cloning solarized repo
    $CLONE $SOLARIZED_GIT $SOLARIZED
  fi
}

setup_solarized
