#!/usr/bin/env zsh

source $(dirname $0)/../sh_functions
cmd=$(basename $0)

description() {
    echo "Stop a vitual machine."
}

usage() {
    echo "`B USAGE`"
    echo "     `C $PROG $cmd` [-h] `U name`"
    echo
    echo "`B DESCRIPTION`"
    echo "     $(description)"
    echo
    echo "     By default, issues an ACPI shutdown message."
    echo "     Run with `C -f` forcefully poweroff."
    echo
    echo "`B WHERE`"
    echo "     `C name`  virtual machine name"
    echo
    echo "`B OPTIONS`"
    echo "     `C -f`      force stop by powering off virtual machine"
    echo "     `C -h`      print this message"
}

force=0

while getopts ":fhH" opt
do
    case $opt in
        f)
            force=1
            ;;
        h)
            usage
            exit
            ;;
        H)
            description
            exit
            ;;
        :)
            echo "-$OPTARG requires an argument; run with -h for help" >&2
            exit 1
            ;;
        \?)
            echo "invalid option -$OPTARG; run with -h for help" >&2
            exit 1
            ;;
    esac
done
shift $(($OPTIND-1))

if [[ $# == 0 ]]
then
    die "virtual machine name not specified; run with -h for help"
fi

name=$1
shift

if [[ $# > 0 ]]
then
    die "too many arguments; run with -h for help"
fi

if [[ $force != 0 ]]
then
    method="poweroff"
else
    method="acpipowerbutton"
fi
VBoxManage controlvm $name $method

# vim: ft=zsh
