#!/usr/bin/env zsh

if [[ $ME_OS == osx ]] ; then
    prepend_path /opt/X11
fi

export XSESSION_LOG=$ME_LOG_DIR/xsession.$ME_HOST.log

xtail() {
    tail -f $XSESSION_LOG
}

alias x='startx 2> $XSESSION_LOG'
alias xlog='xterm -T "X Session" -name log -e tail -f $XSESSION_LOG'
