#!/usr/bin/env zsh

if which keychain > /dev/null 2>&1 ; then
    keychain --quiet
    export KEYCHAIN_ENV=~/.keychain/$(uname -n)-sh
    [[ -f $KEYCHAIN_ENV ]] && source $KEYCHAIN_ENV
fi

keychain_init() {
    keychain_opts="--eval --agents ssh"
    [[ $ME_OS == osx ]] && keychain_opts+=" --inherit any"
    for pub in ~/.ssh/*.pub ; do
        pri=$(basename $pub .pub)
        eval keychain $keychain_opts $pri
    done
}
