#!/usr/bin/env zsh

export RABBITMQ_HOME=$ME_OPT_DIR/rabbitmq/current
append_path $RABBITMQ_HOME

RMQD=rabbitmq-server
RMQ_LOG=$RABBITMQ_HOME/var/log/rabbitmq/rabbitmq.$(hostname).log
RMQ_LOG_CMD="tail -f $RMQ_LOG"

alias rmqd="$RMQD"
alias xrmqd='xterm -title RabbitMQ -name log -e "$RMQD" &'
alias rmqctl=rabbitmqctl

alias rmqlog="$RMQ_LOG_CMD"
alias xrmqlog='xterm -title "RabbitMQ Log" -name log -e "$RMQ_LOG_CMD" &'
