#!/usr/bin/env zsh

FUSION=/Applications/VMware\ Fusion.app/Contents/Library
VMDIRS=(~/Documents/VMs ~/Documents/Virtual\ Machines)

if [[ -d $FUSION ]] ; then
    alias vmrun='$FUSION/vmrun'
fi

# find a vmx file based on vmname
fvmx() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    local name=$1
    local vmx
    set localtoptions nonomatch
    for vmdir in $VMDIRS; do
        [[ -d $vmdir ]] || vmdir=$vmdir.localized
        [[ -d $vmdir ]] || continue
        vmdir=$vmdir/$name
        [[ -d $vmdir ]] || vmdir=$vmdir.vmwarevm
        [[ -d $vmdir ]] && vmx=$(/bin/ls $vmdir/*.vmx)
        if [[ -f $vmx ]]; then
            print $vmx
            return
        fi
    done
    return 1
}

vmstart() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws start "$(fvmx $1)"
}

vmstop() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws stop "$(fvmx $1)"
}

vmreset() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws reset "$(fvmx $1)"
}

vmsuspend() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws suspend "$(fvmx $1)"
}

vmpause() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws pause "$(fvmx $1)"
}

vmplay() {
    if [[ $# != 1 ]]; then
        echo "$0 name"
        return 1
    fi
    vmrun -T ws unpause "$(fvmx $1)"
}
