#!/usr/bin/env zsh

basedir=$(dirname $0)/..
profile_dir=$(dirname $0)/profile.d

for f in $profile_dir/[[:digit:]]* ; do
    source $f
done

if [[ -r $profile_dir/local ]]
then
    source $profile_dir/local
fi

unset _profile_dir
