#!/usr/bin/env zsh

if [ -n "$ME_PROFILE_ENV_LOAD" ]; then
    total_start=$(($(gdate +"%s%3N")))
fi

basedir=$(dirname $0)/..
profile_dir=$(dirname $0)/profile.d


if [[ -r $profile_dir/local.pre ]]
then
    source $profile_dir/local.pre
fi

for f in $profile_dir/[[:digit:]]* ; do
    if [[ $f == *.ps1 ]]; then
        continue
    fi
    if [ -n "$ME_PROFILE_ENV_LOAD" ]; then
        start=$(gdate +%s%3N)
    fi
    source $f
    if [ -n "$ME_PROFILE_ENV_LOAD" ]; then
        stop=$(gdate +%s%3N)
        printf "%0.3i %s\n" $(($stop - $start)) $(basename $f)
        unset start stop
    fi
done

if [[ -r $profile_dir/local.post ]]
then
    source $profile_dir/local.post
fi

unset _profile_dir

if [ -n "$ME_PROFILE_ENV_LOAD" ]; then
    total_stop=$(($(gdate +"%s%3N")))
    printf "%0.3i %s\n" $(($total_stop - $total_start)) "total"
    unset total_start total_stop
fi
