#!/usr/bin/env zsh

basedir=$(dirname $0)/..
profile_dir=$(dirname $0)/profile.d

if [[ -r $profile_dir/local.pre ]]
then
    source $profile_dir/local.pre
fi

for f in $profile_dir/[[:digit:]]* ; do
    if [[ $f == *.ps1 ]]; then
        continue
    fi
    source $f
done

if [[ -r $profile_dir/local.post ]]
then
    source $profile_dir/local.post
fi

unset _profile_dir
