#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

set -e

main () {
  hdr refreshing gradle
  local destdir=$ME_TOOL_DIR/opt
  for version in $ME_GRADLE_VERSIONS; do
    install_version $destdir $version || exit
  done
  link gradle-$ME_GRADLE_VERSIONS[1] $destdir/gradle
}

install_version () {
  local destdir=$1
  local version=$2
  local distfile=gradle-${version}-bin.zip
  local disturl=https://services.gradle.org/distributions/$distfile
  msg installing gradle $version
  msg fetching $disturl
  wget --continue -P $ME_DISTFILE_DIR $disturl || return
  msg extracting $distfile
  mkdir -p $destdir || return
  rm -rf $destdir/gradle-$version
  unzip -qo $ME_DISTFILE_DIR/$distfile -d $destdir || return
}

main $@
