#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

set -e

msg "refreshing homebrew $HOMEBREW_HOME"

[ -d $HOMEBREW_HOME ] && die "homebrew directory already exists: $HOMEBREW_HOME"

mkdir -p $HOMEBREW_HOME
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C $HOMEBREW_HOME
