#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

set -e

version=$ME_TDA_VERSION
disturl=https://github.com/irockel/tda/releases/download
distfile=tda-bin-$version.zip
destdir=$ME_TOOL_DIR/opt/tda-$version

msg installing tda $version
msg fetching tda $version
wget --continue -P $ME_DISTFILE_DIR $disturl/$version/$distfile || exit
msg extracting $distfile
rm -r $destdir || return
mkdir -p $destdir || return
unzip -qo $ME_DISTFILE_DIR/$distfile -d $destdir || return
