#!/usr/bin/env zsh

basedir=$(dirname $0)/../..
source $basedir/etc/profile

set -e
source $ME_LIBEXEC_DIR/sh_functions

version=$ME_TDA_VERSION
disturl=https://github.com/irockel/tda/releases/download
distfile=tda-bin-$version.zip
destdir=$ME_OPT_DIR/tda-$version

msg installing tda $version
msg fetching tda $version
wget --continue -P $ME_DISTFILE_DIR $disturl/$version/$distfile
msg extracting $distfile
[[ -d $destdir ]] && rm -r $destdir
mkdir -p $destdir
unzip -qo $ME_DISTFILE_DIR/$distfile -d $destdir
