#!/usr/bin/env zsh

autoload -U promptinit;     promptinit
autoload -Uz compinit;      compinit -d $ME_ZSH_CACHE_DIR/compdump.$ME_HOST
autoload colors;            colors

for z in $ME_ZSH_CONFIG_DIR/* ; do
    source $z
done
