#!/usr/bin/env zsh

disturl=http://archive.apache.org/dist/ant/binaries
versions=($ME_ANT_VERSION_19 $ME_ANT_VERSION_18)

mkdir -p $ME_OPT_DIR || exit
for version in $versions ; do
    echo refreshing ant version $version
    distfile=apache-ant-${version}-bin.tar.gz
    echo ...fetching
    wget --continue -P $ME_DISTFILE_DIR $disturl/$distfile || exit
    echo ...extracting
    tar xfz $ME_DISTFILE_DIR/$distfile -C $ME_OPT_DIR || exit
done

# vim: ft=zsh
