#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

set -e

main () {
  hdr refreshing dotnet
	local destdir=$ME_PLATFORM_TOOL_DIR/go
  for version in $ME_GO_VERSIONS; do
    install_version $destdir $version
  done
  link goroot-$ME_GO_VERSIONS[1] $destdir/goroot
  link gopath-$ME_GO_VERSIONS[1] $destdir/gopath
}

install_version () {
  local destdir=$1
  local version=$2
  msg installing dotnet $version
  local platform=
  case $ME_PLATFORM in
    linux-x64)
      platform=linux-amd64
      ;;
    osx-x64)
      platform=darwin-amd64
      ;;
    *)
      die "unsupported platform: $ME_PLATFORM"
      ;;
  esac
  local distfile=go${version}.${platform}.tar.gz
  local disturl=https://dl.google.com/go/${distfile}
  msg fetching $disturl
  wget --continue -P $ME_DISTFILE_DIR $disturl
  msg extracting $distfile
  rm -rf $destdir/goroot-$version $destdir/gopath-$version
  mkdir $destdir/goroot-$version $destdir/gopath-$version
  tar xzf $ME_DISTFILE_DIR/$distfile -C $destdir/goroot-$version --strip-components 1
}

main $@
