#!/usr/bin/env zsh

disturl=https://services.gradle.org/distributions
versions=($ME_GRADLE_VERSION_24)
mkdir -p $ME_OPT_DIR || exit
for version in $versions ; do
    echo refreshing gradle version $version
    distfile=gradle-${version}-bin.zip
    echo ...fetching
    wget --continue -P $ME_DISTFILE_DIR $disturl/$distfile || exit
    echo ...extracting
    unzip -oq $ME_DISTFILE_DIR/$distfile -d $ME_OPT_DIR || exit
done

# vim: ft=zsh
