#!/usr/bin/env zsh

disturl=https://dl.bintray.com/groovy/maven
versions=($ME_GROOVY_VERSION_24)
mkdir -p $ME_OPT_DIR
for version in $versions ; do
    echo refreshing groovy dist version $version
    distfile=apache-groovy-binary-${version}.zip
    if [[ ! -f $ME_DISTFILE_DIR/$distfile ]]
    then
        echo ...fetching
        wget --continue -P $ME_DISTFILE_DIR $disturl/$distfile
    else
        echo ...using cache
    fi
    echo ...extracting
    unzip -oq $ME_DISTFILE_DIR/$distfile -d $ME_OPT_DIR
done

# vim: ft=zsh
