#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

src_dir=$ME/.git
tgt_dir=$HOME/.git

[ -e $tgt_dir ] && die "$tgt_dir already exists"
 msg "installed into $(dirname $tgt_dir)"
cp -r $src_dir $tgt_dir
