#!/usr/bin/env zsh

disturl=http://archive.apache.org/dist/maven
versions=($ME_MAVEN_VERSION_33 $ME_MAVEN_VERSION_32 $ME_MAVEN_VERSION_31 $ME_MAVEN_VERSION_30 $ME_MAVEN_VERSION_22)

mkdir -p $ME_MAVEN_HOMES || exit
for version in $versions ; do
    echo fetching maven dist $version
    local major=$(echo $version | cut -d. -f1)
    wget -O - $disturl/maven-$major/$version/binaries/apache-maven-${version}-bin.tar.gz 2> /dev/null \
        | tar xfz - -C $ME_MAVEN_HOMES
done

# vim: ft=zsh
