#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

theme_url=https://raw.githubusercontent.com/mutantmonkey/dotfiles/master/task/zenburn-256.theme
theme=$(basename $theme_url)

msg fetching theme $theme
wget --continue -O $ME_DATA_DIR/task/theme.rc $theme_url

# vim: ft=zsh
