#!/usr/bin/env zsh

source $(dirname $0)/../sh_functions

disturl=http://apache.mirrors.pair.com/tomcat
versions=($ME_TOMCAT_VERSION_85 $ME_TOMCAT_VERSION_80 $ME_TOMCAT_VERSION_70 $ME_TOMCAT_VERSION_60 $ME_TOMCAT_VERSION_90)
mkdir -p $ME_OPT_DIR || exit
for version in $versions ; do
    echo refreshing tomcat version $version
    dist=apache-tomcat-$version
    distfile=$dist.tar.gz
    echo ...fetching
    wget --continue -P $ME_DISTFILE_DIR $disturl/tomcat-${version%%.*.*}/v${version}/bin/$distfile || exit
    if [[ -d $ME_OPT_DIR/$dist ]] ; then
        echo ...remove previous
        rm -rf $ME_OPT_DIR/$dist
    fi
    echo ...extracting
    gnutar xfz $ME_DISTFILE_DIR/$distfile -C $ME_OPT_DIR || exit
    echo ...linking
    shortver=$(echo $version | awk -F. '{print $1$2}')
    shortver=${shortver%%0}
    link=$ME_OPT_DIR/apache-tomcat-$shortver
    rm -f $link
    ln -s $dist $link
done

# vim: ft=zsh
