#!/usr/bin/env zsh

disturl=http://www.gtlib.gatech.edu/pub/apache/tomcat
versions=($ME_TOMCAT_VERSION_85 $ME_TOMCAT_VERSION_80 $ME_TOMCAT_VERSION_70 $ME_TOMCAT_VERSION_60)
mkdir -p $ME_OPT_DIR || exit
for version in $versions ; do
    echo refreshing tomcat version $version
    distfile=apache-tomcat-$version.tar.gz
    echo ...fetching
    wget --continue -P $ME_DISTFILE_DIR $disturl/tomcat-${version%.*.*}/v${version}/bin/$distfile || exit
    echo ...extracting
    tar xfz $ME_DISTFILE_DIR/$distfile -C $ME_OPT_DIR || exit
done

# vim: ft=zsh
