#!/usr/bin/env zsh

basedir=$(dirname $0)/../..

source $basedir/etc/profile
source $ME_LIBEXEC_DIR/sh_functions

set -e

theme_url=https://raw.githubusercontent.com/chriskempson/base16-xresources/master/xresources/base16-zenburn-256.Xresources
theme=$(basename $theme_url)

msg fetching theme $theme
rm -f $ME_DATA_DIR/x/$theme
mkdir -p $ME_DATA_DIR/x
wget -O $ME_DATA_DIR/x/$theme $theme_url
