"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 5000
add_newline = true

palette = 'me'
format = """
╭──── \
[](fg:path)\
$directory\
[](fg:path bg:vcs)\
$git_branch\
$git_status\
[](fg:vcs bg:time)\
$time\
[ ](fg:time)\
$cmd_duration\
$line_break\
╰─ \
$character """

[os]
disabled = false
style = "bg:who fg:text"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Raspbian = "󰐿"
Macos = "󰀵"
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Arch = "󰣇"
Debian = "󰣚"

[username]
show_always = true
style_user = "bg:who fg:text"
style_root = "bg:who fg:text"
format = '[ $user]($style)'

[directory]
style = "bg:path fg:text"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:vcs"
format = '[[ $symbol $branch](fg:text bg:vcs)]($style)'

[git_status]
use_git_executable = true
modified = "${count}"
style = "bg:vcs"
format = '[[ $all_status$ahead_behind](fg:text bg:vcs)]($style)'

[nodejs]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[c]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[lua]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[golang]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[java]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[kotlin]
symbol = " "
style = "bg:lang"
format = '[[ $symbol](fg:text bg:lang)]($style)'

[python]
symbol = " "
style = "bg:lang"
format = '[[ $symbol(\(#$virtualenv\))](fg:text bg:lang)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:time"
format = '[[  $time](fg:text bg:time)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](fg:success)'
error_symbol = '[ ](fg:error)'
vimcmd_symbol = '[ ](fg:edit)'
vimcmd_replace_one_symbol = '[ ](bold fg:edit_select)'
vimcmd_replace_symbol = '[ ](bold fg:edit_select)'
vimcmd_visual_symbol = '[ ](bold fg:edit_select)'

[cmd_duration]
show_milliseconds = true
style = "italic"
disabled = false
show_notifications = true
min_time_to_notify = 1000
format = "[[$duration](fg:time italic)]($style)"

[palettes.me]
edit         = "172"
edit_select  = "123"
error        = "124"
lang         = "246"
path         = "250"
success      = "035"
text         = "000"
time         = "244"
who          = "252"
vcs          = "248"
