$Env:JAVA_ROOT="$Env:ME_PLATFORM_DIR\java"
$Env:JDK8_HOME="$Env:JAVA_ROOT\jdk-8"
$Env:JDK11_HOME="$Env:JAVA_ROOT\jdk-11"
$Env:JDK17_HOME="$Env:JAVA_ROOT\jdk-17"
$Env:JDK21_HOME="$Env:JAVA_ROOT\jdk-21"
$Env:JDK24_HOME="$Env:JAVA_ROOT\jdk-24"

$Env:JDK_HOME="$Env:JDK21_HOME"
$Env:JAVA_HOME="$Env:JDK_HOME"

$ME_PATH = "$ME_PATH;$Env:JDK_HOME\bin"
